// Mock data for rooms - Keep for reference during backend development

export const MOCK_ROOMS = [
  {
    id: "room-1",
    name: "Downtown Coffee",
    type: "text-video" as const,
    participants: 8,
    active: true,
    password: undefined,
  },
  {
    id: "room-2",
    name: "Park Discussion",
    type: "text" as const,
    participants: 12,
    active: true,
    password: undefined,
  },
  {
    id: "room-3",
    name: "Studio Session",
    type: "video" as const,
    participants: 5,
    active: false,
    password: undefined,
  },
  {
    id: "room-4",
    name: "Community Center",
    type: "text-video" as const,
    participants: 15,
    active: true,
    password: undefined,
  },
  {
    id: "room-5",
    name: "Quiet Corner",
    type: "text" as const,
    participants: 3,
    active: false,
    password: undefined,
  },
   {
    id: "room-6",
    name: "Nice Channel",
    type: "text" as const,
    participants: 800,
    active: true,
    password: undefined,
  },
]

// Mock room locations with coordinates for map
export const MOCK_ROOM_LOCATIONS = [
  {
    id: "room-1",
    name: "Downtown Coffee",
    type: "text-video" as const,
    participants: 8,
    lat: 40.7128,
    lng: -74.006,
    active: true,
  },
  {
    id: "room-2",
    name: "Park Discussion",
    type: "text" as const,
    participants: 12,
    lat: 40.7829,
    lng: -73.9654,
    active: true,
  },
  {
    id: "room-3",
    name: "Studio Session",
    type: "video" as const,
    participants: 5,
    lat: 40.7505,
    lng: -73.9972,
    active: false,
  },
  {
    id: "room-4",
    name: "Community Center",
    type: "text-video" as const,
    participants: 15,
    lat: 40.7614,
    lng: -73.9776,
    active: true,
  },
  {
    id: "room-5",
    name: "Quiet Corner",
    type: "text" as const,
    participants: 3,
    lat: 40.7489,
    lng: -73.968,
    active: false,
  },
  {
   id: "room-6",
    name: "Nice Channel",
    type: "text-video" as const,
    participants: 800,
    lat: 8.469353814083625,
    lng: 124.58903109187337,
    active: true,
  },
]
